### ISSUE TITLE
Ketsu Onyos ability doesn't work at Range 0

### ISSUE THREAD

**Issue by ForceM1782** [Sandrem/FlyCasual#1285]
As stated, it works fine at R1 but at R0 there is no option to use it when engagement starts. The card however says it should work at R0

**Comment by Sandrem** [comment]
Fixed

**Comment by simonvogel** [comment]
Actually this is not fixed for me.
Btw Maul crew is missing? Cannot select it on Ketsu
