### ISSUE TITLE
Zam Wesell can have negative charges

### ISSUE THREAD

**Issue by philippebureau** [Sandrem/FlyCasual#3102]
Zam crew let you take extra attack even with 0 charges and goes to -2 charges
![Zam](https://user-images.githubusercontent.com/8918617/105508376-4bb7fc80-5c9a-11eb-84da-ce0945ef71b1.jpg)

**Comment by Sandrem** [comment]
Fixed

**Comment by Immelman51** [comment]
Hi, sorry but this issue is not fixed. 

"You should thank me": 
1st part: the lock acquiring part is ok. 
2nd Part: I can have a bonus attack  even if I have less than 2 charges. Then I can have -2 charges. (screenshot below)
"You'd better mean business"
1st part: doesn't work even if I have 2 charges. When I select "do a bonus attack against the defender", it spends my 2 charges, but there's no attack.
2nd Part: It works fine
![zamminus2](https://user-images.githubusercontent.com/31988939/114311326-97867f00-9aee-11eb-8c4e-998d68ffa303.png)
